In [1]:
import pandas

In [2]:
pandas.__version__

'2.3.1'

In [7]:
import pandas as pd

In [4]:
# Pandas works on Series (ID, Single Columns, ID list etc) and DataFrame (2D, matrix, raw n colm)

In [5]:
data={
    'Empid'     :   [101,102,103,104,105,106,107,108,109,110],
    'Empname'   :   ['Anu','Manu','Raj','Ravi','Sarthak','Manoj','Yogesh','Aman','Suraj','Rahul'],
    'EmpSalary'  :  [23345,45678,22567,34567,45981,56981,66932,77421,89311,97321]
}

In [6]:
print(data)

{'Empid': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 'Empname': ['Anu', 'Manu', 'Raj', 'Ravi', 'Sarthak', 'Manoj', 'Yogesh', 'Aman', 'Suraj', 'Rahul'], 'EmpSalary': [23345, 45678, 22567, 34567, 45981, 56981, 66932, 77421, 89311, 97321]}

In [7]:
df= pd.DataFrame(data)

In [9]:
df

   Empid  Empname  EmpSalary
0    101      Anu      23345
1    102     Manu      45678
2    103      Raj      22567
3    104     Ravi      34567
4    105  Sarthak      45981
5    106    Manoj      56981
6    107   Yogesh      66932
7    108     Aman      77421
8    109    Suraj      89311
9    110    Rahul      97321

In [14]:
# its give me top 5 records
df.head()

   Empid  Empname  EmpSalary
0    101      Anu      23345
1    102     Manu      45678
2    103      Raj      22567
3    104     Ravi      34567
4    105  Sarthak      45981

In [15]:
# its give me bottom five records
df.tail()

   Empid Empname  EmpSalary
5    106   Manoj      56981
6    107  Yogesh      66932
7    108    Aman      77421
8    109   Suraj      89311
9    110   Rahul      97321

In [16]:
# its give me the information about data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    10 non-null     object
 2   EmpSalary  10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [17]:
# its give me the information about numerical columns only
df.describe()

           Empid     EmpSalary
count   10.00000     10.000000
mean   105.50000  56010.400000
std      3.02765  26345.543487
min    101.00000  22567.000000
25%    103.25000  37344.750000
50%    105.50000  51481.000000
75%    107.75000  74798.750000
max    110.00000  97321.000000

In [18]:
df.head(3)

   Empid Empname  EmpSalary
0    101     Anu      23345
1    102    Manu      45678
2    103     Raj      22567

In [19]:
df.Empid

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: Empid, dtype: int64

In [23]:
df['EmpSalary']

0    23345
1    45678
2    22567
3    34567
4    45981
5    56981
6    66932
7    77421
8    89311
9    97321
Name: EmpSalary, dtype: int64

In [24]:
df.EmpSalary.head(4)

0    23345
1    45678
2    22567
3    34567
Name: EmpSalary, dtype: int64

In [25]:
# Aggregate Functions
# sum, max, min, mean, std, shape

In [26]:
df.shape

(10, 3)

In [27]:
df.EmpSalary.sum()

np.int64(560104)

In [28]:
df.EmpSalary.mean()

np.float64(56010.4)

In [29]:
df.EmpSalary.max()

97321

In [30]:
df.EmpSalary.std()

26345.543486517792

In [31]:
df.EmpSalary.min()

22567

In [32]:
import numpy as np

In [36]:
data={
    'Empid'     :   [101,102,103,104,105,106,107,108,109,110],
    'Empname'   :   ['Anu','Manu','Raj',np.nan,'Sarthak','Manoj','Yogesh','Aman','Suraj','Rahul'],
    'EmpSalary'  :  [23345,np.nan,22567,34567,45981,56981,66932,np.nan,89311,97321]
}

In [37]:
df=pd.DataFrame(data)

In [38]:
df

   Empid  Empname  EmpSalary
0    101      Anu    23345.0
1    102     Manu        NaN
2    103      Raj    22567.0
3    104      NaN    34567.0
4    105  Sarthak    45981.0
5    106    Manoj    56981.0
6    107   Yogesh    66932.0
7    108     Aman        NaN
8    109    Suraj    89311.0
9    110    Rahul    97321.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    9 non-null      object
 2   EmpSalary  8 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 372.0+ bytes

In [42]:
# its giving me number of missing values in each columns
df.isnull().sum()

Empid        0
Empname      1
EmpSalary    2
dtype: int64

In [44]:
# its giving me total number of missing value in entire data set
df.isnull().sum().sum()

np.int64(3)

In [45]:
# Handle Missing Value => REMOVE, REPLACE, REPAIR

In [46]:
df.dropna()

   Empid  Empname  EmpSalary
0    101      Anu    23345.0
2    103      Raj    22567.0
4    105  Sarthak    45981.0
5    106    Manoj    56981.0
6    107   Yogesh    66932.0
8    109    Suraj    89311.0
9    110    Rahul    97321.0

In [47]:
df.fillna(value=0)

   Empid  Empname  EmpSalary
0    101      Anu    23345.0
1    102     Manu        0.0
2    103      Raj    22567.0
3    104        0    34567.0
4    105  Sarthak    45981.0
5    106    Manoj    56981.0
6    107   Yogesh    66932.0
7    108     Aman        0.0
8    109    Suraj    89311.0
9    110    Rahul    97321.0

In [48]:
df.Empname.fillna('Missing')

0        Anu
1       Manu
2        Raj
3    Missing
4    Sarthak
5      Manoj
6     Yogesh
7       Aman
8      Suraj
9      Rahul
Name: Empname, dtype: object

In [49]:
df.EmpSalary.fillna(5000)

0    23345.0
1     5000.0
2    22567.0
3    34567.0
4    45981.0
5    56981.0
6    66932.0
7     5000.0
8    89311.0
9    97321.0
Name: EmpSalary, dtype: float64

In [50]:
df

   Empid  Empname  EmpSalary
0    101      Anu    23345.0
1    102     Manu        NaN
2    103      Raj    22567.0
3    104      NaN    34567.0
4    105  Sarthak    45981.0
5    106    Manoj    56981.0
6    107   Yogesh    66932.0
7    108     Aman        NaN
8    109    Suraj    89311.0
9    110    Rahul    97321.0

In [57]:
# its give me the option to save the data with the changes
df.Empname=df.Empname.fillna('No Name')

In [58]:
df

   Empid  Empname  EmpSalary
0    101      Anu    23345.0
1    102     Manu        NaN
2    103      Raj    22567.0
3    104  No Name    34567.0
4    105  Sarthak    45981.0
5    106    Manoj    56981.0
6    107   Yogesh    66932.0
7    108     Aman        NaN
8    109    Suraj    89311.0
9    110    Rahul    97321.0

In [59]:
df.EmpSalary.mean()

np.float64(54625.625)

In [60]:
df.EmpSalary.fillna(0).mean()

np.float64(43700.5)

In [61]:
# Replacing Value with Average
df.EmpSalary= df.EmpSalary.fillna(df.EmpSalary.mean())

In [62]:
df

   Empid  Empname  EmpSalary
0    101      Anu  23345.000
1    102     Manu  54625.625
2    103      Raj  22567.000
3    104  No Name  34567.000
4    105  Sarthak  45981.000
5    106    Manoj  56981.000
6    107   Yogesh  66932.000
7    108     Aman  54625.625
8    109    Suraj  89311.000
9    110    Rahul  97321.000

In [8]:
# for read any excel file
df=pd.read_excel("C:/Users/Sumit/Documents/Python Learning/Croma Campus/Python with Jupyter Notebook/Day-26/Financial_Sample.xlsx")

In [9]:
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15.0,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15.0,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15.0,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014
698,Government,Canada,Paseo,High,723.0,10,7.0,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,250,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014

In [68]:
df.shape

(700, 16)

In [69]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15.0,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15.0,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

In [70]:
df.isnull().sum()

Segment                 8
Country                11
Product                 8
Discount Band          62
Units Sold              5
Manufacturing Price     0
Sale Price              7
Gross Sales             5
Discounts               5
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              692 non-null    object
 1   Country              689 non-null    object
 2   Product              692 non-null    object
 3   Discount Band        638 non-null    object
 4   Units Sold           695 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           693 non-null    float64
 7   Gross Sales          695 non-null    float64
 8   Discounts            695 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(7), int64(3), object(5)
memory usage: 87.6+ KB

In [73]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [84]:
for col in df.columns:
    if df[col].isnull().sum()>0:
        print(col,'\t', df[col].isnull().sum(),'\t',df[col].dtype)

Segment 	 8 	 object
Country 	 11 	 object
Product 	 8 	 object
Discount Band 	 62 	 object
Units Sold 	 5 	 float64
Sale Price 	 7 	 float64
Gross Sales 	 5 	 float64
Discounts 	 5 	 float64

In [85]:
df['Segment']

0            Government
1            Government
2             Midmarket
3             Midmarket
4             Midmarket
             ...
695      Small Business
696      Small Business
697          Government
698          Government
699    Channel Partners
Name: Segment, Length: 700, dtype: object

In [86]:
# To find out no of missing value in a column
df.isnull().sum().sum()

np.int64(111)

In [88]:
# % of missing value in column
111/700

0.15857142857142856

In [10]:
# to find most repeating value in a column
df['Segment'].mode()

0    Government
Name: Segment, dtype: object

In [90]:
df['Segment'].unique()

array(['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
       'Small Business', nan], dtype=object)

In [92]:
df['Segment'].value_counts()

Segment
Government          294
Midmarket           100
Enterprise          100
Small Business      100
Channel Partners     98
Name: count, dtype: int64

In [11]:
# filling missing values in object column by mode(most_frequent Value)

for col in df.select_dtypes(include='object').columns:
    print(col,'\t', df[col].isnull().sum(),'\tReplaced By-> ',df[col].mode()[0])
    df[col]=df[col].fillna(df[col].mode()[0])

Segment 	 8 	Replaced By->  Government
Country 	 11 	Replaced By->  France
Product 	 8 	Replaced By->  Paseo
Discount Band 	 62 	Replaced By->  High
Month Name 	 0 	Replaced By->  October

In [12]:
df.isnull().sum()

Segment                 8
Country                11
Product                 8
Discount Band          62
Units Sold              5
Manufacturing Price     0
Sale Price              7
Gross Sales             5
Discounts               5
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [18]:
# filling missing values in float column by mean(Average)

for col in df.select_dtypes(include='float').columns:
    if df[col].isnull().sum()>0:
        print(col,'\t', df[col].isnull().sum(),'\tReplaced By->',round(df[col].mean(),2))
        df[col]=df[col].fillna(round(df[col].mean(),2))

Units Sold 	 5 	Replaced By-> 1607.88
Sale Price 	 7 	Replaced By-> 117.91
Gross Sales 	 5 	Replaced By-> 183967.04
Discounts 	 5 	Replaced By-> 13077.16

In [19]:
df.isnull().sum()

Segment                 8
Country                11
Product                 8
Discount Band          62
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64